import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "../globals.css"
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { getCurrentUser } from "@/lib/auth/user-auth";

const geistSans = ({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Only what the Navbar needs — never OTP fields or the password hash.
  const user = await getCurrentUser();
  const sessionUser = user
    ? { fullName: user.fullName, image: user.image, verified: user.verified }
    : null;

  return (
    <html
      lang="en"
      className={` ${poppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <Navbar user={sessionUser} />

        {children}
        <Footer />
        </body>
    </html>
  );
}
